{% set version = "2.0.0" %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: 2c125ca28c37ae011db888ce38cfc0fcbcd03b670bc890ffe72427477eafc86a
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: 7d7e04ce03f9ea97609d5a23f138d054a68f08c040d2031398c071664f7a6b4b

build:
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m poetry build && pip install jsonschema-gentypes --find-links dist --no-index --no-deps
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - poetry >=1.0.0
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python >=3.8
    - pip
  run:
    - jsonschema
    - python >=3.8
    - pyyaml
    - referencing
    - typing-extensions
    - requests

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - pip
    - pytest-cov
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - pytest src/tests -vv -k "not test_name" --cov=jsonschema_gentypes --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=64

about:
  home: https://github.com/camptocamp/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
