{% set version = "1.5.0" %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: 6d53f22ea850023ca3af60b9a9425f2c75bb83faffa5463e18e78c1c1a6c7a0c
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: 9e1eb6e38267898fa48f6ff6788d15a5b356a4fad754af751a405b5852fa94fd

build:
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jsonschema
    - ruamel.yaml

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - pip
    - pytest-cov
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - pytest src/tests -vv -k "not test_name" --cov=jsonschema_gentypes --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=70

about:
  home: https://github.com/camptocamp/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
