{% set version = "2.8.0" %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: 176a5ae4de9c1dcff1c7f6a5de5b5441fcdc2db7b6d7892d35aaef3ac938476b
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: e35478c177878cd534ffc7b5a388eef160e9f1d958c9bf50b0a883563b37cc30

build:
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m poetry build && pip install -vv jsonschema-gentypes --find-links=dist --no-index --no-deps
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.0
    - poetry-core
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python >=3.9
  run:
    - jsonschema
    - python >=3.9
    - pyyaml
    - referencing
    - requests
    - typing-extensions

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - coverage
    - pip
    - pytest
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - cd src && coverage run --source=jsonschema_gentypes -m pytest -vv --color=yes --tb=long -k "not test_name"
    - coverage report --show-missing --skip-covered --fail-under=59

about:
  home: https://github.com/camptocamp/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
