{% set version = "2.3.0" %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: 923eaf059fafdaa10348d3e233790143dfcad13a0e93ff5d2a5dfc81aa726383
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: 870067b9f0ba917748161795fcbb421f878302b99b682f201794d83cc13ac0e2

build:
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m poetry build && pip install -vv jsonschema-gentypes --find-links=dist --no-index --no-deps
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.0
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python >=3.8
  run:
    - jsonschema
    - python >=3.8
    - pyyaml
    - referencing
    - requests
    - typing-extensions

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - pip
    - pytest-cov
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - pytest src/tests -vv -k "not test_name" --cov=jsonschema_gentypes --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=61

about:
  home: https://github.com/camptocamp/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
