{% set version = "2.9.3" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: 3ff49735aba5bd23e7f736e3553444226defdafe89a83dc2f2c6799a6d500f34
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: d5e5d3d39804b623a8fe9fa274058c4c4ec755e70a45aebf922e41eba8ac6089

build:
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m poetry build && pip install -vv jsonschema-gentypes --find-links=dist --no-index --no-deps
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.0
    - poetry-core
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python {{ python_min }}
  run:
    - jsonschema
    - python >={{ python_min }}
    - pyyaml
    - referencing
    - requests
    - typing-extensions

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - coverage
    - pip
    - pytest
    - python {{ python_min }}
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - cd src && coverage run --source=jsonschema_gentypes -m pytest -vv --color=yes --tb=long -k "not test_name"
    - coverage report --show-missing --skip-covered --fail-under=59

about:
  home: https://github.com/sbrunner/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
