{% set version = "1.4.1" %}

package:
  name: jsonschema-gentypes
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-{{ version }}.tar.gz
    sha256: a5662ce969c898aebd36bf8d0c6e0f9162f176877d57f916b9f83284d7951af9
  - folder: src
    url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/{{ version }}.tar.gz
    sha256: eb5738c4c5d83b711d0f0a6e1942cafc6e0943712257b5c71e26327510209aac

build:
  noarch: python
  script:
    # trust ``poetry``-generated ``setup.py``
    - {{ PYTHON }} -c "__import__('pathlib').Path('dist/pyproject.toml').unlink()"
    - cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jsonschema
    - ruamel.yaml

test:
  source_files:
    - src/tests
  imports:
    - jsonschema_gentypes
  requires:
    - pip
    - pytest-cov
    - pyyaml
    - requests
  commands:
    - pip check
    - jsonschema-gentypes --help
    - pytest src/tests -vv -k "not test_name" --cov=jsonschema_gentypes --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=70

about:
  home: https://github.com/camptocamp/jsonschema-gentypes
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: src/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
