# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.11.0"

package:
  name: jsonschema-gentypes
  version: ${{ version }}

source:
  # use upstream wheel due to hopeless mess of hard-pinned poetry(-core) plugins
  - url: https://pypi.org/packages/py3/j/jsonschema-gentypes/jsonschema_gentypes-${{ version }}-py3-none-any.whl
    sha256: a8737def3bfe9bf7359bfd93b4fce6fc2d4fcf068f47c353e205d58927b23c18
    file_name: jsonschema_gentypes-${{ version }}-py3-none-any.whl
  - url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/${{ version }}.tar.gz
    sha256: f586d7530bc85243b03139ea842116bbbad25ee0fe4f3a28a645b94755407a7f
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install jsonschema-gentypes -vv --no-deps --find-links=. --no-index --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - jsonschema
    - python >=${{ python_min }}
    - pyyaml
    - referencing
    - requests
    - typing-extensions

tests:
  - python:
      imports: jsonschema_gentypes
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - pytest
        - python ${{ python_min }}.*
        - pyyaml
        - requests
    script:
      - pip check
      - jsonschema-gentypes --help
      - cd src
      - coverage run --source=jsonschema_gentypes -m pytest -vv --color=yes --tb=long -k "not (test_name or test_validate_bad_config)"
      - coverage report --show-missing --skip-covered --fail-under=70

about:
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: src/LICENSE
  homepage: https://github.com/sbrunner/jsonschema-gentypes

extra:
  recipe-maintainers:
    - bollwyvl
