# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.10.0

package:
  name: jsonschema-gentypes
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jsonschema-gentypes/jsonschema_gentypes-${{ version }}.tar.gz
    sha256: 44370063298ebe7ddc8af300d7e4f69ab68cc142e73aa700b8d7ade1291f44b2
    target_directory: dist
  - url: https://github.com/camptocamp/jsonschema-gentypes/archive/refs/tags/${{ version }}.tar.gz
    sha256: 6de92b12ddf7ce0586bd992794e0e7f106c26e10f4e7871f36c0bc7f2f5a08a5
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m poetry build
    - ${{ PYTHON }} -m pip install -vv jsonschema-gentypes --find-links=dist --no-index --no-deps
  python:
    entry_points:
      - jsonschema-gentypes = jsonschema_gentypes.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.0
    - poetry-core
    - poetry-dynamic-versioning
    - poetry-plugin-tweak-dependencies-version
    - python ${{ python_min }}.*
  run:
    - jsonschema
    - python >=${{ python_min }}
    - pyyaml
    - referencing
    - requests
    - typing-extensions

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - jsonschema_gentypes
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - pytest
        - python ${{ python_min }}.*
        - pyyaml
        - requests
    script:
      - pip check
      - jsonschema-gentypes --help
      - cd src
      - coverage run --source=jsonschema_gentypes -m pytest -vv --color=yes --tb=long -k "not test_name"
      - coverage report --show-missing --skip-covered --fail-under=59

about:
  summary: Tool to generate Python types based on TypedDict from a JSON Schema
  license: BSD-2-Clause
  license_file: dist/LICENSE
  homepage: https://github.com/sbrunner/jsonschema-gentypes

extra:
  recipe-maintainers:
    - bollwyvl
